# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180504_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='/', upload_to='articles/'),
        ),
    ]
