# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsletterform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterForm',
            new_name='NewsLetterRecipients',
        ),
    ]
